### ISSUE TITLE
Is this to rewrite rayo ?

### ISSUE THREAD

**Issue by waghanza** [GetRayo/rayo.cr#1]
Hi,

Is this project for a re-write ?

It could be also useful (not sure) to have API manager (such as [kemal](https://github.com/kemalcr/kemal)) that run in behind `rayo` (using [Duktape](https://github.com/jessedoyle/duktape.cr) as javascript  engine).

Regards,

**Comment by aichholzer** [comment]
Hey @waghanza. This ist actually intended to be a http server written in Crystal. I just haven't had the time yet to get around doing it.
